export const gardenConfig = {
  title: 'Yellow Garden',
  date: '21 · 09',
  flowerCount: 12,
  defaultSeed: 'primavera',
  audio: true,
  secrets: true,
  growthDuration: 4.8,
  bloomDuration: 3.2,
  bouquetDuration: 3.6,
  unwrapDuration: 1.5,
  scatterDuration: 2.2,
  heartDuration: 2.8,
  messageDuration: 3,
  surpriseDuration: 3.5,
};
